version: '3.7'
services:
  app1:
    image: ryanpurchase288/app1:latest
    build: ./app1 
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    deploy:
      replicas: 1
    
       
  app2:
    image: ryanpurchase288/app2:latest      
    build: ./app2
    ports:
      - target: 5001
        protocol: tcp
    deploy:
      replicas: 1  
  app3:
    image: ryanpurchase288/app3:latest
    build: ./app3
    ports:
      - target: 5002
        protocol: tcp
    deploy:
      replicas: 1 
  app4:
    image: ryanpurchase288/app4:latest      
    build: ./app4
    ports:
      - target: 5003
        protocol: tcp
    deploy:
      replicas: 1
  nginx:
    image: nginx:alpine
    ports:
     - target: 80
       published: 80
       protocol: tcp
    deploy:
      replicas: 1
